/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 
package cbrknnmeningitis;

import db.CasesDBManager;
import db.TableViewer;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import utility.Util;

/**
 *
 * @author Fiqih Amrullah
 */
public class FormBobot extends javax.swing.JFrame 
{
     private List<ParameterAttribute> listpa;

    /** Creates new form FormBobot */
    public FormBobot() {
        initComponents(); 
        Util.TengahWindow(this);
        setResizable(false);        
        setTitle("Pengolahan Data Bobot");       
        loadDataWeights();
        
    }
    
     public void loadDataWeights()
     {
        CasesDBManager cdbmanager = new CasesDBManager();     
        listpa = cdbmanager.loadAttributeWeights();
        if (listpa.size()>0)
        {
          jtblatributmeningitis.setModel(TableViewer.ConvertWeightsListToTableModel(listpa));
        }else
        {
          jtblatributmeningitis.setModel(TableViewer.ConvertMengitisListToTableModel());    
        }
     } 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblatributmeningitis = new javax.swing.JTable();
        jbtnTutup = new javax.swing.JButton();
        jbtnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pengolahan Data Bobot");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("PENGOLAHAN DATA BOBOT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Entri Bobot"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblatributmeningitis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblatributmeningitis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblatributmeningitisMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtblatributmeningitis);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 380, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 53, 419, 460));

        jbtnTutup.setText("Tutup");
        jbtnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTutupActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 519, 150, 50));

        jbtnSimpan.setText("Simpan");
        jbtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 519, 170, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jtblatributmeningitisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblatributmeningitisMouseClicked
// TODO add your handling code here:
     
}//GEN-LAST:event_jtblatributmeningitisMouseClicked

private void jbtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSimpanActionPerformed
// TODO add your handling code here:
    // TODO add your handling code here:
   
     List<ParameterAttribute> listpa = new ArrayList<ParameterAttribute>();
  
    for(int i=0;i<jtblatributmeningitis.getRowCount();i++)
    {
        ParameterAttribute pa  = new ParameterAttribute(jtblatributmeningitis.getValueAt(i, 1).toString());
        pa.setWeight(Double.parseDouble(jtblatributmeningitis.getValueAt(i, 2).toString()));
         
        listpa.add(pa); 
    }
    
     
    CasesDBManager cdb = new CasesDBManager();
    cdb.saveWeights(listpa);
    JOptionPane.showMessageDialog(this, "Data Bobot Berhasil Disimpan!","Sukses",JOptionPane.INFORMATION_MESSAGE);
    
}//GEN-LAST:event_jbtnSimpanActionPerformed

private void jbtnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTutupActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_jbtnTutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormBobot().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnSimpan;
    private javax.swing.JButton jbtnTutup;
    private javax.swing.JTable jtblatributmeningitis;
    // End of variables declaration//GEN-END:variables
}
